### ISSUE TITLE
/data/config and /data/data are missing

### ISSUE THREAD

**Issue by ivan98** [crazy-max/docker-qbittorrent#1]
#### Steps to reproduce this issue

1. `docker run -d --name qb -v /mnt/my-big-raid5-volume:/data crazymax/qbittorrent`

#### Expected behaviour

ln `/data`, the following folders should be present:
config, data, downloads, temp, torrents, watch and webui

#### Actual behaviour

ln `/data`, only the following folders are present:
downloads, temp, torrents, watch and webui

This is because `/data/config` and `/data/data` are created in `Dockerfile`. When a storage volume is mounted onto /data, they get hidden.

**Comment by crazy-max** [comment]
Please create a proper bug report (Configuration, Docker info, logs missing). Thanks
