### ISSUE TITLE
Don't  combine RUN's in builder image

### ISSUE THREAD

**Issue by sedlund** [crazy-max/docker-qbittorrent#2]
https://github.com/crazy-max/docker-qbittorrent/blob/587a94dd07fdb1a5b86f434d61668916a52f2f54/Dockerfile#L7

There is no need to combine RUN lines in the builder stage for a 'flatter' image.  The builder image will be discarded.  Leaving them as separate RUN statements will let the build host cache things more efficiently and debugging the build will be a lot easier and faster.

**Comment by crazy-max** [comment]
@sedlund Feel free to open a PR, thanks!
